name: React Template CD
on:
  push:
    branches: 
      - master
jobs:          
  build-and-deploy-to-S3:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [12.x]
      steps:
        - name: Extract branch name
          shell: bash
          run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}
          id: get_branch_name

        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{matrix.node}}
            cache: yarn

        - name: Installing dependencies
          run: yarn

        - name: Build App
          run: yarn build

        - name: Deploy to S3
          uses: jakejarvis/s3-sync-action@master
          with:
           args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: 'build'
            DEST_DIR: ${{ steps.get_branch_name.outputs.branch }}